# Created by Jekyll Writer
title: Kpali's Blogs
author: Kpali
description: 我所说的都是错的
permalink: '/:year/:month/:day/:title/'
paginate: 6
paginate_path: '/page/:num/'
github_username: kpali
gems:
  - jekyll-paginate
markdown: kramdown
baseurl: /blog
