# Site settings
title: Kpali's Blog
email: kpali@qq.com
description: >
  我所说的都是错的
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "https://kpali.github.io" # the base hostname & protocol for your site

permalink: '/:year/:month/:day/:title/'
paginate: 6
paginate_path: '/page/:num/'

# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
filter: 'category'


# Social account
# twitter:  username
# weibo:    ID
github:   kpali
# codepen:  username
# dribbble: username


# Comment
# disqus_shortname: discussion_shortname


# Google Analytics
# google_analytics: tracking_ID


# Build settings
markdown: kramdown
sass:
  style: compressed
gems:
  - jekyll-paginate
